@baseUrl = http://localhost:8080/api/v1

###
#Create User

POST {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json

{
    "username": "teste2@teste.com",
    "password": "123456"
}

###
#Get User

GET {{baseUrl}}/usuarios/109
Accept: application/json
Content-Type: application/json

###
#Get User

GET {{baseUrl}}/usuarios/110
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODkzODk4LCJleHAiOjE3NTU4OTU2OTgsInJvbGUiOiJDTElFTlRFIn0.4JKN8rimIucZYHwtQHM5VWY7AJaW4rsq-14hCgKzuFY"

###
#Update Password of User

PATCH {{baseUrl}}/usuarios/108
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3NTU4OTM1NDAsImV4cCI6MTc1NTg5NTM0MCwicm9sZSI6IkFETUlOIn0.4FNb9mt6Kmx5FlDYwoE9O71M3kKoT7OlazSOxApomL0"

{
    "senhaAtual": "111111",
    "novaSenha": "123456",
    "confirmaSenha": "123456"
}

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json


###
#Auth
POST http://localhost:8080/api/v1/auth
Accept: application/json
Content-Type: application/json

{
    "username": "teste1@teste.com",
    "password": "123456"
}

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODkzNDYyLCJleHAiOjE3NTU4OTUyNjIsInJvbGUiOiJDTElFTlRFIn0.EDhIUVFn3wKffHsDrH4KM7E1SGJk9ebTKxjUznAVc08"

###
