@baseUrl = http://localhost:8080/api/v1

###
#Create User

POST {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json

{
    "username": "citrano@email.com",
    "password": "123456"
}

###
#Get User

GET {{baseUrl}}/usuarios/109
Accept: application/json
Content-Type: application/json

###
#Get User

GET {{baseUrl}}/usuarios/109
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODk1MzE2LCJleHAiOjE3NTU4OTcxMTYsInJvbGUiOiJDTElFTlRFIn0.GN0HG38HCQX4hoXd9fQuJ8qkNPrB46V7HB-CKy8b6d8"

###
#Update Password of User

PATCH {{baseUrl}}/usuarios/109
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODk1MzE2LCJleHAiOjE3NTU4OTcxMTYsInJvbGUiOiJDTElFTlRFIn0.GN0HG38HCQX4hoXd9fQuJ8qkNPrB46V7HB-CKy8b6d8"

{
    "senhaAtual": "123456",
    "novaSenha": "123456",
    "confirmaSenha": "123456"
}

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3NTU4OTU2NDYsImV4cCI6MTc1NTg5NzQ0Niwicm9sZSI6IkFETUlOIn0.XMutNnbC0PMfbbHZVoJlgJXK5RvSIOpYx_PewPcZs6w"


###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODk1MzE2LCJleHAiOjE3NTU4OTcxMTYsInJvbGUiOiJDTElFTlRFIn0.GN0HG38HCQX4hoXd9fQuJ8qkNPrB46V7HB-CKy8b6d8"

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3NTU5NTgyNjYsImV4cCI6MTc1NTk2MDA2Niwicm9sZSI6IkNMSUVOVEUifQ.WSl1L8YqqryzUAM2udGP4pCoN21hP_xEI3NavpLuJQo

###

#Create User

POST {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json

{
    "username": "beltrano@email.com",
    "password": "123456"
}

###
#Auth
POST http://localhost:8080/api/v1/auth
Accept: application/json
Content-Type: application/json

{
    "username": "altrano@email.com",
    "password": "123456"
}


###

#Create Client

POST {{baseUrl}}/clientes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiZWx0cmFub0BlbWFpbC5jb20iLCJpYXQiOjE3NTU5NzI1ODAsImV4cCI6MTc1NTk3NDM4MCwicm9sZSI6IkNMSUVOVEUifQ.k_L5-NLayX0JiR1Uak9UQOMIcwadQQeR5v5kn3dWKKs

{
    "nome": "Beltrano",
    "cpf": "10390511030"
}

###

#Get All Clients

GET {{baseUrl}}/clientes?size=1&page=1&sord=id_asc
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHRyYW5vQGVtYWlsLmNvbSIsImlhdCI6MTc1NTk3NDY4MywiZXhwIjoxNzU1OTc2NDgzLCJyb2xlIjoiQURNSU4ifQ.fbKGVmCp7rAo0WtGB6YuQPws09UhW-Z0P5TptrHy9Zk

###
