@baseUrl = http://localhost:8080/api/v1

###
#Create User

POST {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json

{
    "username": "citrano@email.com",
    "password": "123456"
}

###
#Get User

GET {{baseUrl}}/usuarios/109
Accept: application/json
Content-Type: application/json

###
#Get User

GET {{baseUrl}}/usuarios/109
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODk1MzE2LCJleHAiOjE3NTU4OTcxMTYsInJvbGUiOiJDTElFTlRFIn0.GN0HG38HCQX4hoXd9fQuJ8qkNPrB46V7HB-CKy8b6d8"

###
#Update Password of User

PATCH {{baseUrl}}/usuarios/109
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODk1MzE2LCJleHAiOjE3NTU4OTcxMTYsInJvbGUiOiJDTElFTlRFIn0.GN0HG38HCQX4hoXd9fQuJ8qkNPrB46V7HB-CKy8b6d8"

{
    "senhaAtual": "123456",
    "novaSenha": "123456",
    "confirmaSenha": "123456"
}

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3NTU4OTU2NDYsImV4cCI6MTc1NTg5NzQ0Niwicm9sZSI6IkFETUlOIn0.XMutNnbC0PMfbbHZVoJlgJXK5RvSIOpYx_PewPcZs6w"


###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZTFAdGVzdGUuY29tIiwiaWF0IjoxNzU1ODk1MzE2LCJleHAiOjE3NTU4OTcxMTYsInJvbGUiOiJDTElFTlRFIn0.GN0HG38HCQX4hoXd9fQuJ8qkNPrB46V7HB-CKy8b6d8"



###
#Auth
POST http://localhost:8080/api/v1/auth
Accept: application/json
Content-Type: application/json

{
    "username": "altrano@email.com",
    "password": "123456"
}

###
#Get All Users

GET {{baseUrl}}/usuarios
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBlbWFpbC5jb20iLCJpYXQiOjE3NTU5NTgyNjYsImV4cCI6MTc1NTk2MDA2Niwicm9sZSI6IkNMSUVOVEUifQ.WSl1L8YqqryzUAM2udGP4pCoN21hP_xEI3NavpLuJQo

###

#Create Client

POST {{baseUrl}}/clientes
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbHRyYW5vQGVtYWlsLmNvbSIsImlhdCI6MTc1NTk1ODUwNiwiZXhwIjoxNzU1OTYwMzA2LCJyb2xlIjoiQ0xJRU5URSJ9.kKuzRPp5qNiFROP5zK7_aJdiv3949cuPxcG6oyTOLrA

{
    "name": "Altrano",
    "cpf": "23288386003"
}

###
